version: '3'

services:
  apache:
    image: ohmy/apache-php7.2-prod
    ports:
      - 8081:80
    volumes:
      - ./srv/www/html:/var/www/html    #здесь расположены сайты
      - ./srv/apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./srv/apache/logs:

  nginx:
    image: nginx:lastest
    ports:
      - 80:80
    volumes:
      - ./srv/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./srv/nginx/logs:

  mysql:
    image: mysql:lastest
    ports:
      - 3307:3306
    volumes:
      - ./srv/mysql/conf:
      - ./srv/mysql/logs:
    environment:
      MYSQL_ROOT_PASSWORD: root
